### ISSUE TITLE
Interviewfragen überlegen

### ISSUE THREAD

**Issue by p2sk** [Narua2010/Projekt-1-Vision-und-Konzept#1]
Für die verschiedenen Interviews sollten geeignete Fragen konzipiert werden.

* Sollten unterschiedliche Fragen für Experten und Kunstinteressierte vorliegen?
* Was wollen wir über das Archiv, die Artefakte, die Wünsche und Erwartungen herausfinden?

**Comment by Narua2010** [comment]
* Was versprechen sich die Interviewten kurzfristig/langfristig von dem Projekt?
* Soll das Archive primär für Kunsthistoriker und Wissenschaftler sein? Oder soll es sich an die breite Masse richten? Oder doch nur zur Sicherung der Werke und Daten dienen?
* Wie stellen sich die Interviewpartner die Darstellung vor? - Ggf. Diskussion? Vorschläge und Gegenvorschläge? Was ist möglich?
* Wie soll die Darstellung für Menschen mit Behinderung aussehen? Zum Beispiel für Menschen mit Sehbehinderung?
* Gibt es die Möglichkeit 3D-Scans der Bilder anzulegen? Möglichkeit für 3D-Ansichten, virtuelle Räume (Virtual Reality/Augmented Reality)
* Wird das Archive primär über den Browser besucht? Oder soll eine Art Desktopanwendung geben die darauf zugreift?

**Comment by annasubach** [comment]
- Welche technische Hardware steht Ihnen zur Verfügung wenn Sie im Internet künstlerische Artefakte ansehen?
- Welchen Browser benutzen Sie wenn Sie im Web surfen?
- Die Darstellung welcher Inhalte interessiert Sie am meisten wenn Sie diese Anwendung in Anspruch nehmen würden? (z.B. Texte zu den Kunstwerken, die Kunstwerke selber oder Schichtaufnahmen)
- Allgemeine Fragen: Wie alt sind Sie? Wie oft besuchen Sie ein Museum? Wie oft suchen sie nach künstlerischen Artefakten im Netz?

**Comment by javadalam** [comment]
Welche Materialien können wir verwenden? (z.B Wir sollten Adobe Photoshop lernen ) 
Welche Datenbank ist besser für unser Projekt ?

**Comment by p2sk** [comment]
- Welche Artefakte kommen für eine raffinierte Darstellung in Frage (welches Artefakt weißt viele Bilder auf)?
- Welche Erkenntnisse erwarten Sie sich aus einer raffinierten Darstellung erschließen zu können, die physisch nicht möglich wäre?
- Was können Sie zu den relevanten Artefakten erzählen?
- Wie liegen die Artefakte als Datenbestand vor?
- Welche Aufzeichnungen umfasst das Archiv über die bekannten Formen noch?
- Wäre Partizipation in einer raffinierten Darstellung gewünscht?

**Comment by Shabnamramzani** [comment]
- Soll das Projekt nur für bestimmte Gruppen dargestellt werden? 
- Welche Zielgruppe kommen in Betracht (z.B. verschiedenen Erfahrungen und Informationen über Kunst, Jungendliche die sich für Kunst interessieren, andere Künstler)?

_<sub>edit Pascal: Dopplung raus und Fragen strukturiert </sub>_

**Comment by javadalam** [comment]
- Welche Materialien können wir verwenden? (z.B Wir sollten Adobe Photoshop lernen )
- Welche Datenbank ist besser für unser Projekt ?
