### ISSUE TITLE
Interview 1 - Expertin aus LCA Projekt

### ISSUE THREAD

**Issue by Shabnamramzani** [Narua2010/Projekt-1-Vision-und-Konzept#3]
#3 Dokumentation liegt im wiki (Ideensammlung und Interview 22.11.2020) https://github.com/Narua2010/Projekt-1-Vision-und-Konzept/wiki/Ideensammlung-und-Interview-22.11.2020

**Comment by javadalam** [comment]
Herr Pascal Schorde hat am 20.11.2020 ein Interview mit Frau Anja Bertels durchgeführt, die Ergebnisse des Interviews können Sie im Wiki einsehen.
https://github.com/Narua2010/Projekt-1-Vision-und-Konzept/wiki/Interview-Anja-Bertels-20.11.2020

Frau Anna Subach führte das nächste Interview am 22.11.2020, die Ergebnisse des Interviews können im Wiki eingesehen werden.
https://github.com/Narua2010/Projekt-1-Vision-und-Konzept/wiki/Interview-22.11.2020

**Comment by Shabnamramzani** [comment]
Closed #3
